### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [Shadow-Java/Shadow-Java#1]
It has been noticed that while using athul/waka-readme@master your WAKATIME_API_KEY 80c337d3-a4df-4e70-a117-e6b8f62c8dc3 is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by Shadow-Java** [comment]
> It has been noticed that while using athul/waka-readme@master your WAKATIME_API_KEY 80c337d3-a4df-4e70-a117-e6b8f62c8dc3 is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.
that's ok,just your dashboard.if you care about this,you can follow this https://github.com/athul/waka-readme
